function [fitresult, gof] = createFit_PR(r, p)
%CREATEFIT(R,P)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: r
%      Y Output: p
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Nov-2022 21:39:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( r, p );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.151526082015343 -0.000910805832110311 -0.151526081735736 -0.0643354752865309];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'p vs. r', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'r', 'Interpreter', 'none' );
ylabel( 'p', 'Interpreter', 'none' );
grid on


